import manifestJson from '../../public/img/manifest.json'

/**
 * One entry per slug in assets/raw/, generated by scripts/optimize-images.mjs.
 * `width`/`height` are the source's own dimensions — used for the rendered
 * <img>'s width/height attributes, which is what actually prevents layout
 * shift (the browser reserves the right aspect ratio before the file loads).
 */
export type ImageManifestEntry = {
  width: number
  height: number
  formats: Record<'avif' | 'webp' | 'jpg', { width: number; path: string }[]>
}

export type ImageManifest = Record<string, ImageManifestEntry>

/**
 * Starts as {} in a fresh checkout (the committed baseline — see
 * .gitignore) and fills in as photos are added to assets/raw/ and the
 * pipeline re-run. Never edited by hand.
 */
export const imageManifest: ImageManifest = manifestJson
